### PR TITLE
fix for detecting big sur (and newer) versions of macOS

### PR DESCRIPTION
**Pull request by smnogar**
A slight tweak to okalachev's PR that should work for Big Sur 11.X and future macOS releases.

### CODE REVIEW

**Comment by bjajoh** [comment]
@smnogar Have you been able to build ROS noetic for Big Sur with your fix?

**Comment by smnogar** [comment]
@bjajoh Yes, with surprisingly few patches necessary! I'll post the build instructions to https://github.com/smnogar/ros-install-osx next week.

**Comment by bjajoh** [comment]
> @bjajoh Yes, with surprisingly few patches necessary! I'll post the build instructions to https://github.com/smnogar/ros-install-osx next week.

Awesome, I'm really interested, have you been able to build desktop? Or desktop-full?

**Comment by smnogar** [comment]
Desktop full

**Comment by bjajoh** [comment]
@smnogar Did you have time to write the instructions? I'm really really interested and can't wait :D 
I can also help you to write it nicely down, if you tell me what to do.

**Comment by smnogar** [comment]
Finally updated my install instructions for Big Sur and noetic. Check them out [here](https://github.com/smnogar/ros-install-osx)

**Comment by schvarcz** [comment]
@smnogar Thank you!

I succeeded to run your script after few attempts. Most of things I had to do manually were related to my local installation and library versions. However, I also confirmed that in a fresh Mac everything works like a charm.

**Comment by christophebedard** [comment]
@cottsay / @nuclearsandwich could you take a look at this?

**Comment by Leo-Simpson** [comment]
It seems that `rosdep update` is still experiencing the error `unrcognized version: 11.2 `(the latest Big Sur version). 

Do you have an idea how to fix this ? Thanks a lot !

**Comment by christophebedard** [comment]
> Do you have an idea how to fix this ? Thanks a lot !

Yes, this PR fixes it:

```
% python3 -m rospkg.os_detect
OS Name:     osx
OS Version:  11.2.1
OS Codename: big sur
```

It just needs to get merged.

**Comment by bjajoh** [comment]
I just changed the lines of code locally on my system, it just worked fine. :)

**Comment by christophebedard** [comment]
sure that's an option too 😁

for anyone looking for a quick fix after installing `rosdep`:

```
% pip3 install git+https://github.com/smnogar/rospkg.git@bigsur
```

**Comment by Leo-Simpson** [comment]
Ah sorry I did not see it did not merge yet, thanks !

And @christophebedard thank you for the shortcut!

**Comment by Leo-Simpson** [comment]
Hello again, 

I don't know if it is the right way to post an issue, but as it looks that many people here succeeded to make  [the ros-installer](https://github.com/smnogar/ros-install-osx) working, so I give it a try.

I still get this issue about `qt_gui_cpp` not installing , because of `SIP binding generator NOT available.` I tried with running `brew link qt --force` before, but without success.

Should I open a PR in https://github.com/smnogar/ros-install-osx for that ?

Thank you in advance !

**Review by cottsay — COMMENTED** [review]
This change looks good to me, but I have one question.

The previous behavior when detecting on an unknown/unsupported version of macOS was to raise `OsNotDetected`, which forced an updated to this package to list the new codename. This change will cause all `11.x` versions in the future to be detected as `big sur`, which may not be correct, right?

Previously, the code opted to "say nothing" rather than "say something incorrect".

**Comment by christophebedard** [comment]
> This change will cause all 11.x versions in the future to be detected as big sur, which may not be correct, right?

They seem to be pumping out `11.x` releases every couple of months, so it's going to be annoying to update. It seems like they switched to `11.x`, but yeah there's no way to know for sure. Your call.

**Comment by christophebedard** [comment]
> Are they all still called 'Big Sur'? Meaning that the codename-to-version relationship changed?

I'm pretty sure yeah:

* https://www.wikiwand.com/en/MacOS_Big_Sur#/Release_history
* https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_1-release-notes
* https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_2-release-notes
* https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_3-beta-release-notes

**Review by cottsay — APPROVED** [review]
> I'm pretty sure yeah

Sounds good, thanks for the info.

**Review by wjwwood — APPROVED** [review]

**Review by nuclearsandwich — APPROVED** [review]

**Pull request merged**
