### PR TITLE
Support for Manjaro Linux

### PR DESCRIPTION
**Pull request by jaume-gasa**
Added support for Manjaro Linux (distro based on Arch Linux)

https://manjaro.org

### CODE REVIEW

**Comment by wjwwood** [comment]
See: https://github.com/ros-infrastructure/rosdep/issues/507

**Comment by jaume-gasa** [comment]
@wjwwood  I was able to run ```rosdep update``` correctly (https://imgur.com/a/JrJwu) and without the error I posted in ros-infrastructure/rosdep#507

**Comment by wjwwood** [comment]
Great, thanks for the confirmation.

**Comment by wjwwood** [comment]
I'm not sure when this change will be released (that's up to @dirk-thomas to decide when) but that would include `python-rospkg` (ubuntu) and `rospkg` in `pip` getting updated.  Separately, I don't know when the arch equivalent package would get updated.

**Comment by dirk-thomas** [comment]
@wjwwood There is no reason anyone else can do releases of this package.

Since there are no other pending patches this should be released now (rather than wait for an undefined amount of time). I just released version 1.1.1.

**Comment by wjwwood** [comment]
I just figured that we should batch them up, which I would leave to you. I wasn't thinking to release just for this patch, but that's fine too.

**Pull request merged**
